[project]
name = "a2a-trigonometry-agent"
version = "0.1.0"
description = "Google's A2A protocol-based trigonometry agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.3.3",
    "notebook>=7.4.3",
    "python-a2a>=0.5.9",
    "requests>=2.32.4",
]
